version: '3.9'
services:
  tictacwallet:
    image: sasmeka/tictacwallet
    ports:
      - '8083:8001'
    networks:
      - gonet
    environment:
      - PGHOST=172.18.0.2
      - PGDATABASE=tictac_database
      - PGUSER=fazz
      - PGPASSWORD=abcd1234
      - PGPORT=5432
      # - WHITELIST=https://glistening-taffy-bfdcf2.netlify.app,http://localhost:3000

networks:
  gonet:
    name: devnet
    external: true
